appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {linux_aarch64: default, linux_ppc64le: azure, win: azure}
travis:
  secure: {BINSTAR_TOKEN: m4eyYHouIpmESwDAncCn3PaAAf5mVCoLDctWSpjWPP0JDEq51ezHAgHBt0c+fW8BmOozckOZHHRJWjzauz6SxqQGu3OIgJMQzQHVe4isIebktI2aTTbJsDasWbJsAVbe8K+ALJZcNuAmRx5/BgdgbugjHjS1WQnOtT9OplneBADJ7tc6VW9RQG5dYDGnKZ+Z8W089taMyE/D7q7bPzVkfDFiOTY/dhslAQYIX3fLQX1pldBUi9yLZ8qbbSYapHq/O3OG23EtnkkguEyjHBPG/qRzEFYx2Tn487pLy6HzqrwXa69Su/yCO1ma6vJZM8dSBo84cchxFbrABdkv273sB1gtnThixusm9hGd6Al7VyHiTW25R+oJ4gCnKR3+AWwDvSQCClVHPOSA6M/0+xh/USJDoP6KUGzunAQvzpIFLut3v0G+AUdV7mpwrluFwWC88m3qVNEqQATNbou4WSOmEo+eJ7wL3hCef+iyUjerVn4zY1TigyWLFJ5c5UZG6wcB+tBYtD3gk64uar+/oGTLArcNlw+flL0deuSi/sG/7MaTOxAIHzBpCbQIYvPQSH9ecmJv7KYIstzhmxVCRSP6RSktiplEy5KlUB0wPu/goqvU4Imk3ples2Zuy1KvdYXRImGdX53Q17fyzQ2PeANbh8SAPe4S4awxpFWyhxzOfhY=}
bot:
  automerge: true
conda_forge_output_validation: true
